Repository pathwar/pathwar, pull requests merged in 2019-10, with the labels that each got.

#154 feat: /teams API endpoint
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwengine/api_dev_dbdump.go
  go/pkg/pwengine/api_dev_generatefakedata.go
  go/pkg/pwengine/api_dev_getinfo.go
  go/pkg/pwengine/api_pub_getstatus.go
  go/pkg/pwengine/api_pub_listlevels.go
  go/pkg/pwengine/api_pub_listteams.go
  go/pkg/pwengine/api_pub_ping.go
  go/pkg/pwengine/engine.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  swagger.yaml
Labels: 🔍 Ready for Review

#155 chore: add githooks
  githooks/pre-commit
  githooks/pre-commit.d/generate
  githooks/pre-commit.d/lint
Labels: 🔍 Ready for Review

#157 chore: update web to match new API format
  web/src/actions/tournaments.js
  web/src/components/levels/LevelCardPreview.js
  web/src/components/teams/AllTeamsList.js
  web/src/components/teams/UserTeamsList.js
  web/src/components/tournament/AllTeamTournamentsList.js
  web/src/components/tournament/AllTournamentsList.js
  web/src/pages/TournamentPage.js
Labels: 🔍 Ready for Review

#150 feat: screenshoter
  tool/screenshoter/Dockerfile
  tool/screenshoter/Makefile
  tool/screenshoter/docker-compose.yml
  tool/screenshoter/go.mod
  tool/screenshoter/go.sum
  tool/screenshoter/main.go
  tool/screenshoter/out/.gitkeep
Labels: 🔍 Ready for Review

#160 chore: add API testing + testing utilities
  .codecov.yml
  AUTHORS
  go/.golangci.yml
  go/Makefile
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/pwdb/db.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/testing.go
  go/pkg/pwengine/api_dev_dbdump.go
  go/pkg/pwengine/api_dev_generatefakedata.go
  go/pkg/pwengine/api_dev_getinfo.go
  go/pkg/pwengine/api_pub_getstatus.go
  go/pkg/pwengine/api_pub_getstatus_test.go
  go/pkg/pwengine/api_pub_getusersession.go
  go/pkg/pwengine/api_pub_listlevels.go
  go/pkg/pwengine/api_pub_listteams.go
  go/pkg/pwengine/api_pub_ping.go
  go/pkg/pwengine/api_pub_ping_test.go
  go/pkg/pwengine/auth.go
  go/pkg/pwengine/engine.go
  go/pkg/pwengine/engine_test.go
  go/pkg/pwengine/testing.go
  go/pkg/pwserver/doc.go
  go/pkg/pwserver/server.go
  go/pkg/pwserver/server_test.go
  go/pkg/pwserver/testing.go
  go/pkg/pwsso/testing.go
Labels: 🔍 Ready for Review

#158 new API calls
  Makefile
  api/pwdb.proto
  api/pwengine.proto
  deployments/platform/docker-compose.yml
  docs/gen.sum
  go/gen.sum
  go/go.mod
  go/go.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_pub_getusersession.go
  go/pkg/pwengine/api_pub_getusersession_test.go
  go/pkg/pwengine/api_pub_setpreferences.go
  go/pkg/pwengine/api_pub_setpreferences_test.go
  go/pkg/pwengine/auth_test.go
  go/pkg/pwengine/errors.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  go/pkg/pwsso/testing.go
  swagger.yaml
Labels: 🔍 Ready for Review

#163 Chore: update metadata
  web/gatsby-config.js
Labels: 🔍 Ready for Review

#164 WIP feat: GET /tournament/teams API endoint
  .gitattributes
  api/pwdb.proto
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/go.mod
  go/go.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_pub_listtournamentteams.go
  go/pkg/pwengine/api_pub_listtournamentteams_test.go
  go/pkg/pwengine/api_pub_setpreferences.go
  go/pkg/pwengine/api_pub_setpreferences_test.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  go/pkg/pwengine/testing_test.go
  swagger.yaml
Labels: 🚧 WIP

#169 chore: configure grpc-gateway to allow body in set-preferences
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  swagger.yaml
Labels: 🔍 Ready for Review

#170 wip: unix levels/challenges update
  .gitignore
  challenges/unix/fmtstr-hi/docker-compose.yml
  challenges/unix/fmtstr-hi/scripts/patch_level
  challenges/unix/fmtstr-hi/unix/Dockerfile
  challenges/unix/fmtstr-hi/unix/level.c
  challenges/unix/fmtstr-hi/unix/on-init
  challenges/unix/unix1/docker-compose.yml
  challenges/unix/unix1/scripts/patch_level
  challenges/unix/unix1/unix/Dockerfile
  challenges/unix/unix1/unix/level.c
  challenges/unix/unix1/unix/on-init
Labels: ✅ Approved

#171 chore: cleanup challenges that require some more work (will be reverted in an open PR)
  challenges/example/hello-world/Dockerfile
  challenges/example/hello-world/Makefile
  challenges/example/hello-world/on-init
  challenges/example/hello-world/static/index.html
  challenges/unix/fmtstr-hi/docker-compose.yml
  challenges/unix/fmtstr-hi/unix/Dockerfile
  challenges/unix/fmtstr-hi/unix/level.c
  challenges/unix/fmtstr-hi/unix/on-init
  challenges/unix/unix1/docker-compose.yml
  challenges/unix/unix1/unix/Dockerfile
  challenges/unix/unix1/unix/level.c
  challenges/unix/unix1/unix/on-init
  challenges/web/training-tools/docker-compose.yml
  challenges/web/training-tools/front/Dockerfile
  challenges/web/training-tools/front/on-init
  challenges/web/training-tools/front/www/css/base.min.css
  challenges/web/training-tools/front/www/index.html
Labels: 🔍 Ready for Review

#173 chore: cleanup testing challenge which requires some more work (will …
  challenges/web/testing/Dockerfile
  challenges/web/testing/Makefile
  challenges/web/testing/docker-compose-dev.yml
  challenges/web/testing/docker-compose.yml
  challenges/web/testing/patches/srv/shelljs/config.json
  challenges/web/testing/supervisord.conf
Labels: ✅ Approved

#182 feat: add pprof debugger
  go/Makefile
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/pwserver/server.go
Labels: t/platform, 🔍 Ready for Review

#181 feat: Issue/165 Implementing preferences, get Teams on Tournament
  web/package-lock.json
  web/package.json
  web/src/actions/tournaments.js
  web/src/actions/userSession.js
  web/src/api/tournaments.js
  web/src/components/ProtectedRoute.js
  web/src/components/SiteWrapper.js
  web/src/components/tournament/AllTeamTournamentsList.js
  web/src/components/tournament/AllTeamsOnTournamentList.js
  web/src/constants/actionTypes.js
  web/src/pages/AllTournamentsPage.js
  web/src/pages/TournamentPage.js
  web/src/pages/app.js
  web/src/state/tournamentReducer.js
  web/src/styles/layout/loader.css
Labels: t/front, 🔍 Ready for Review

#208 WIP chore: switch to int64 ids (snowflake)
  AUTHORS
  api/pwdb.proto
  api/pwengine.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/go.mod
  go/go.sum
  go/internal/testutil/doc.go
  go/internal/testutil/logging.go
  go/pkg/pwdb/db.go
  go/pkg/pwdb/errors.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwdb/testing.go
  go/pkg/pwengine/api_dev_generatefakedata.go
  go/pkg/pwengine/api_pub_getstatus_test.go
  go/pkg/pwengine/api_pub_getusersession.go
  go/pkg/pwengine/api_pub_getusersession_test.go
  go/pkg/pwengine/api_pub_listtournamentteams.go
  go/pkg/pwengine/api_pub_listtournamentteams_test.go
  go/pkg/pwengine/api_pub_ping_test.go
  go/pkg/pwengine/api_pub_setpreferences.go
  go/pkg/pwengine/api_pub_setpreferences_test.go
  go/pkg/pwengine/auth.go
  go/pkg/pwengine/auth_test.go
  go/pkg/pwengine/engine.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/testing.go
  go/pkg/pwengine/testing_test.go
  go/pkg/pwserver/server.go
  go/pkg/pwserver/testing.go
  go/pkg/pwsso/client.go
  go/pkg/pwsso/keycloak.go
  go/pkg/pwsso/testing.go
  swagger.yaml
Labels: 🚧 WIP

#210 feat: return gRPC responses indirectly to be more future-proof
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwengine/api_pub_listchallenges.go
  go/pkg/pwengine/api_pub_listteams.go
  go/pkg/pwengine/api_pub_listtournamentteams.go
  go/pkg/pwengine/pwengine.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#209 feat: add GET /tournament/team
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/errors.go
  go/pkg/pwengine/api_pub_gettournamentteam.go
  go/pkg/pwengine/api_pub_gettournamentteam_test.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  go/pkg/pwengine/testing_test.go
  swagger.yaml
Labels: 🔍 Ready for Review

#211 chore: explicit errors
  go/Makefile
  go/gen.sum
  go/pkg/pwdb/errors.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwengine/api_pub_getusersession.go
  go/pkg/pwengine/api_pub_listchallenges.go
  go/pkg/pwengine/api_pub_listteams.go
  go/pkg/pwsso/token.go
Labels: 🔍 Ready for Review

#212 GET /challenge?challenge_id=xxx
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwengine/api_pub_getchallenge.go
  go/pkg/pwengine/api_pub_getchallenge_test.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  go/pkg/pwengine/testing_test.go
  swagger.yaml
Labels: 🔍 Ready for Review

#214 feat: updated and added imageboard challenge
  challenges/web/imageboard/docker-compose.yml
  challenges/web/imageboard/front/Dockerfile
  challenges/web/imageboard/front/on-init
  challenges/web/imageboard/front/www/admin.php
  challenges/web/imageboard/front/www/db.php
  challenges/web/imageboard/front/www/get.php
  challenges/web/imageboard/front/www/images/test.jpg
  challenges/web/imageboard/front/www/index.php
  challenges/web/imageboard/mysql/Dockerfile
  challenges/web/imageboard/mysql/bootstrap.sql
Labels: ✅ Approved

#220 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 🔍 Ready for Review

#217 chore: build web directory on change only
  netlify.toml
Labels: 🔍 Ready for Review

#218 feat: create challenges details routing and mainpage - issue/203
  web/src/actions/tournaments.js
  web/src/api/tournaments.js
  web/src/components/challenges/ChallengeCardPreview.js
  web/src/constants/actionTypes.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/app.js
  web/src/pages/styles/ChallengeDetailsPage.module.css
  web/src/state/tournamentReducer.js
Labels: 🔍 Ready for Review

#221 feat: ux-improement: improving list loadings
  netlify.toml
  web/src/components/ProtectedRoute.js
  web/src/components/challenges/ChallengeCardPreview.js
  web/src/components/tournament/AllTeamsOnTournamentList.js
  web/src/pages/TournamentPage.js
  web/src/pages/app.js
  web/src/styles/layout/loader.css
  web/src/styles/layout/loader.module.css
Labels: 🔍 Ready for Review

#222 chore: naming -> Tournament->Season, Team->Organization, TournamentTeam->Team
  AUTHORS
  api/pwdb.proto
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/entity.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_challenge-get.go
  go/pkg/pwengine/api_challenge-get_test.go
  go/pkg/pwengine/api_challenge-list.go
  go/pkg/pwengine/api_organization-list.go
  go/pkg/pwengine/api_pub_gettournamentteam_test.go
  go/pkg/pwengine/api_pub_listteams.go
  go/pkg/pwengine/api_pub_listtournamentteams.go
  go/pkg/pwengine/api_pub_listtournamentteams_test.go
  go/pkg/pwengine/api_pub_ping.go
  go/pkg/pwengine/api_pub_setpreferences.go
  go/pkg/pwengine/api_pub_setpreferences_test.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwengine/api_team-get_test.go
  go/pkg/pwengine/api_team-list.go
  go/pkg/pwengine/api_team-list_test.go
  go/pkg/pwengine/api_tool-dbdump.go
  go/pkg/pwengine/api_tool-generate-fake-data.go
  go/pkg/pwengine/api_tool-info.go
  go/pkg/pwengine/api_tool-info_test.go
  go/pkg/pwengine/api_tool-ping.go
  go/pkg/pwengine/api_tool-status.go
  go/pkg/pwengine/api_tool-status_test.go
  go/pkg/pwengine/api_user-get-session.go
  go/pkg/pwengine/api_user-get-session_test.go
  go/pkg/pwengine/api_user-set-preferences.go
  go/pkg/pwengine/api_user-set-preferences_test.go
  go/pkg/pwengine/auth.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  go/pkg/pwengine/testing_test.go
  rules.mk
  swagger.yaml
Labels: 🔍 Ready for Review

#224 chore: prod compose update
  deployments/platform/docker-compose.yml
Labels: 🔍 Ready for Review

#223 chore: pwserver testing
  go/cmd/pathwar/main.go
  go/go.mod
  go/go.sum
  go/pkg/pwdb/entity.go
  go/pkg/pwserver/server.go
  go/pkg/pwserver/server_test.go
  go/pkg/pwserver/testing.go
Labels: 🔍 Ready for Review

#215 circleci config file update to build and test challenges
  .circleci/config.yml
Labels: 🚧 WIP

#225 fix: typo in API
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  swagger.yaml
Labels: 🔍 Ready for Review

#230 chore: improve debug
  go/cmd/pathwar/main.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwserver/server.go
Labels: 🔍 Ready for Review

#231 chore: add api-unsafe.pathwar.land deploy
  deployments/platform-dev/Makefile
  deployments/platform-dev/docker-compose.yml
Labels: 🔍 Ready for Review

#232 feat: add simple api integration tests
  web/.env.development
  web/.env.production
  web/.env.test
  web/config/jest/__mocks__/file-mock.js
  web/config/jest/jest-preprocess.js
  web/config/jest/loadershim.js
  web/jest.config.js
  web/package-lock.json
  web/package.json
  web/src/actions/seasons.js
  web/src/api/organizations.js
  web/src/api/seasons.js
  web/src/api/tests/api.test.js
  web/src/components/organizations/AllOrganizationsList.js
  web/src/components/organizations/UserOrganizationsList.js
  web/src/components/season/AllTeamsOnSeasonList.js
  web/src/pages/LogoutPage.js
  web/src/pages/SeasonPage.js
Labels: t/front, t/platform, ✅ Approved, 🔍 Ready for Review
