Repository pathwar/pathwar, pull requests merged in 2019-11, with the labels that each got.

#235 feat: Turn active_season_id, team_id and challange_id dynamic on tests
  web/.env.test
  web/src/api/tests/api.test.js
Labels: 🔍 Ready for Review

#239 chore: new prod Makefile commands
  deployments/platform-dev/Makefile
Labels: ✨ Merged

#238 feat: add POST /user/delete-account
  api/pwdb.proto
  api/pwengine.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/entity.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_user-delete-account.go
  go/pkg/pwengine/api_user-delete-account_test.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  swagger.yaml
  web/src/api/tests/api.test.js
Labels: t/platform, ✨ Merged

#242 chore: add hack sparrow's bitmoji pictures
  assets/hack-sparrow/bitmoji/bitmoji-1.jpg
  assets/hack-sparrow/bitmoji/bitmoji-10.jpg
  assets/hack-sparrow/bitmoji/bitmoji-11.jpg
  assets/hack-sparrow/bitmoji/bitmoji-12.jpg
  assets/hack-sparrow/bitmoji/bitmoji-13.jpg
  assets/hack-sparrow/bitmoji/bitmoji-14.jpg
  assets/hack-sparrow/bitmoji/bitmoji-15.jpg
  assets/hack-sparrow/bitmoji/bitmoji-16.jpg
  assets/hack-sparrow/bitmoji/bitmoji-17.jpg
  assets/hack-sparrow/bitmoji/bitmoji-18.jpg
  assets/hack-sparrow/bitmoji/bitmoji-19.jpg
  assets/hack-sparrow/bitmoji/bitmoji-2.jpg
  assets/hack-sparrow/bitmoji/bitmoji-20.jpg
  assets/hack-sparrow/bitmoji/bitmoji-21.jpg
  assets/hack-sparrow/bitmoji/bitmoji-22.jpg
  assets/hack-sparrow/bitmoji/bitmoji-3.jpg
  assets/hack-sparrow/bitmoji/bitmoji-4.jpg
  assets/hack-sparrow/bitmoji/bitmoji-5.jpg
  assets/hack-sparrow/bitmoji/bitmoji-6.jpg
  assets/hack-sparrow/bitmoji/bitmoji-7.jpg
  assets/hack-sparrow/bitmoji/bitmoji-8.jpg
  assets/hack-sparrow/bitmoji/bitmoji-9.jpg
Labels: 🔍 Ready for Review

#246 chore: add new Makefile rules for deployment
  challenges/web/training-sqli/docker-compose.yml
  deployments/platform-dev/Makefile
Labels: t/infra, 🔍 Ready for Review

#248 Assets website
  assets/.netlify/.gitignore
  assets/.netlify/README.md
  assets/.netlify/assets/css/bootstrap.min.css
  assets/.netlify/assets/css/main.css
  assets/.netlify/assets/images/ai-icon.png
  assets/.netlify/assets/images/pathwar-favicon.png
  assets/.netlify/assets/images/pathwar-logo.png
  assets/.netlify/assets/images/pathwar-logo.svg
  assets/.netlify/assets/images/pdf-icon.png
  assets/.netlify/assets/images/plain-icon.png
  assets/.netlify/assets/images/psd-icon.png
  assets/.netlify/assets/images/zip-icon.png
  assets/.netlify/config.yml
  assets/.netlify/layouts/_default/list.html
  assets/.netlify/layouts/_default/single.html
  assets/.netlify/layouts/categories/list.html
  assets/.netlify/layouts/partials/asset-image.html
  assets/.netlify/layouts/partials/foot.html
  assets/.netlify/layouts/partials/head.html
  assets/.netlify/layouts/partials/thumbnail.html
  assets/.netlify/netlify.toml
  assets/.netlify/package-lock.json
  assets/.netlify/package.json
  assets/.netlify/scripts/generate-content.js
  web/netlify.toml
Labels: ✅ Approved

#250 feat: delete account on settings page - issue/240
  web/src/actions/seasons.js
  web/src/actions/userSession.js
  web/src/api/seasons.js
  web/src/api/tests/api.test.js
  web/src/api/userSession.js
  web/src/components/SiteWrapper.js
  web/src/constants/actionTypes.js
  web/src/pages/SeasonPage.js
  web/src/pages/SettingsPage.js
  web/src/pages/app.js
Labels: t/front, 🔍 Ready for Review

#252 chore: retrieve challenge subscription in season challenge list
  go/pkg/pwengine/api_challenge-subscription-close_test.go
  go/pkg/pwengine/api_challenge-subscription-validate_test.go
  go/pkg/pwengine/api_season-challenge-buy_test.go
  go/pkg/pwengine/api_season-challenge-list.go
Labels: 🔍 Ready for Review

#254 chore: compose boilerplate
  challenges/web/training-sqli/docker-compose-ready.yml
  challenges/web/training-sqli/docker-compose-tmp.yml
  challenges/web/training-sqli/docker-compose.yml
  challenges/web/training-sqli/training-sqli.dab
  go/cmd/pathwar/main.go
  go/pkg/pwcompose/compose.go
Labels: 🔍 Ready for Review

#251 Issue/204 - challenge flow (buy, validate, close)
  web/package-lock.json
  web/package.json
  web/src/actions/seasons.js
  web/src/actions/userSession.js
  web/src/api/seasons.js
  web/src/components/challenges/ChallengeCardPreview.js
  web/src/constants/actionTypes.js
  web/src/pages/SeasonPage.js
  web/src/pages/app.js
  web/src/state/seasonReducer.js
Labels: t/front, 🔍 Ready for Review

#256 fix: improve validate and close tests, using right endpoint
  web/src/api/tests/api.test.js
Labels: 🔍 Ready for Review

#259 chore: return challenge validations on POST /challenge-subscription/validate
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_challenge-subscription-validate.go
  go/pkg/pwengine/api_challenge-subscription-validate_test.go
  go/pkg/pwengine/api_season-challenge-get.go
  go/pkg/pwengine/api_season-challenge-get_test.go
  go/pkg/pwengine/api_season-challenge-list.go
  go/pkg/pwengine/api_season-challenge-list_test.go
  go/pkg/pwengine/helpers.go
  go/pkg/pwengine/testing_test.go
Labels: 🔍 Ready for Review

#260 chore: nested proto messages
  Makefile
  api/pwcompose.proto
  api/pwengine.proto
  docs/gen.sum
  go/Makefile
  go/gen.sum
  go/pkg/pwcompose/pwcompose.pb.go
  go/pkg/pwcompose/pwcompose.pb.gw.go
  go/pkg/pwengine/api_challenge-get.go
  go/pkg/pwengine/api_challenge-get_test.go
  go/pkg/pwengine/api_challenge-list.go
  go/pkg/pwengine/api_challenge-subscription-close.go
  go/pkg/pwengine/api_challenge-subscription-close_test.go
  go/pkg/pwengine/api_challenge-subscription-validate.go
  go/pkg/pwengine/api_challenge-subscription-validate_test.go
  go/pkg/pwengine/api_organization-list.go
  go/pkg/pwengine/api_season-challenge-buy.go
  go/pkg/pwengine/api_season-challenge-buy_test.go
  go/pkg/pwengine/api_season-challenge-get.go
  go/pkg/pwengine/api_season-challenge-get_test.go
  go/pkg/pwengine/api_season-challenge-list.go
  go/pkg/pwengine/api_season-challenge-list_test.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwengine/api_team-get_test.go
  go/pkg/pwengine/api_team-list.go
  go/pkg/pwengine/api_team-list_test.go
  go/pkg/pwengine/api_tool-info.go
  go/pkg/pwengine/api_tool-info_test.go
  go/pkg/pwengine/api_tool-status.go
  go/pkg/pwengine/api_tool-status_test.go
  go/pkg/pwengine/api_user-delete-account.go
  go/pkg/pwengine/api_user-delete-account_test.go
  go/pkg/pwengine/api_user-get-session.go
  go/pkg/pwengine/api_user-set-preferences.go
  go/pkg/pwengine/api_user-set-preferences_test.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  rules.mk
  swagger.yaml
  web/Makefile
Labels: 🔍 Ready for Review

#236 feat: web+platform integration tests
  .circleci/config.yml
  Makefile
  go/.dockerignore
  go/docker-compose.yml
  tool/integration/Makefile
  tool/integration/docker-compose.override.yml
  web/.dockerignore
  web/.env.docker-integration
  web/package.json
  web/src/api/tests/api.test.js
Labels: t/front, t/infra, t/platform, 🔍 Ready for Review

#261 `pathwar compose prepare`
  go/cmd/pathwar/main.go
  go/go.mod
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: t/platform, ✅ Approved

#262 chore: get rid of forestadmin
  deployments/platform-dev/docker-compose.yml
  tool/forestadmin/.dockerignore
  tool/forestadmin/.forestadmin-schema.json
  tool/forestadmin/.gitignore
  tool/forestadmin/Dockerfile
  tool/forestadmin/app.js
  tool/forestadmin/bin/www
  tool/forestadmin/middlewares/forestadmin/index.js
  tool/forestadmin/middlewares/welcome/index.js
  tool/forestadmin/middlewares/welcome/template.txt
  tool/forestadmin/models/achievement.js
  tool/forestadmin/models/auth_method.js
  tool/forestadmin/models/coupon.js
  tool/forestadmin/models/coupon_validation.js
  tool/forestadmin/models/event.js
  tool/forestadmin/models/hypervisor.js
  tool/forestadmin/models/index.js
  tool/forestadmin/models/inventory_item.js
  tool/forestadmin/models/level.js
  tool/forestadmin/models/level_flavor.js
  tool/forestadmin/models/level_instance.js
  tool/forestadmin/models/level_subscription.js
  tool/forestadmin/models/level_validation.js
  tool/forestadmin/models/level_version.js
  tool/forestadmin/models/notification.js
  tool/forestadmin/models/team.js
  tool/forestadmin/models/team_member.js
  tool/forestadmin/models/tournament.js
  tool/forestadmin/models/tournament_member.js
  tool/forestadmin/models/tournament_team.js
  tool/forestadmin/models/user.js
  tool/forestadmin/models/user_session.js
  tool/forestadmin/models/whoswho_attempt.js
  tool/forestadmin/package-lock.json
  tool/forestadmin/package.json
  tool/forestadmin/public/favicon.png
  tool/forestadmin/routes/.gitkeep
Labels: 🔍 Ready for Review

#247 feat: team flow: TeamCreate
  .circleci/config.yml
  api/pwdb.proto
  api/pwengine.proto
  docs/gen.sum
  go/Makefile
  go/docker-compose.dev.yml
  go/gen.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_team-accept-invite.go
  go/pkg/pwengine/api_team-create.go
  go/pkg/pwengine/api_team-create_test.go
  go/pkg/pwengine/api_team-send-invite.go
  go/pkg/pwengine/pwengine.pb.go
  go/pkg/pwengine/pwengine.pb.gw.go
  swagger.yaml
  web/src/api/tests/api.test.js
Labels: t/platform, 🔍 Ready for Review

#263 feat: pathwar compose up
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: t/platform, ✅ Approved

#258 fix: validate flow, challenge validations check
  web/src/actions/seasons.js
  web/src/actions/userSession.js
  web/src/api/seasons.js
  web/src/api/tests/api.test.js
  web/src/components/challenges/ChallengeCardPreview.js
  web/src/pages/SettingsPage.js
Labels: t/front, 🔍 Ready for Review

#265 Fix/test package - isolate tests
  tool/integration/Makefile
  tool/integration/docker-compose.override.yml
  web/tests/.env.docker-integration
  web/tests/Dockerfile
  web/tests/api.test.js
  web/tests/config/jest/__mocks__/file-mock.js
  web/tests/config/jest/jest-preprocess.js
  web/tests/config/jest/loadershim.js
  web/tests/jest.config.js
  web/tests/package-lock.json
  web/tests/package.json
Labels: ✅ Approved

#266 chore: small fixes
  go/cmd/pathwar/main.go
Labels: 🔍 Ready for Review

#267 chore: improve delete account
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_challenge-get.go
  go/pkg/pwengine/api_challenge-subscription-close.go
  go/pkg/pwengine/api_challenge-subscription-validate.go
  go/pkg/pwengine/api_organization-list.go
  go/pkg/pwengine/api_season-challenge-buy.go
  go/pkg/pwengine/api_season-challenge-get.go
  go/pkg/pwengine/api_season-challenge-list.go
  go/pkg/pwengine/api_team-create.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwengine/api_team-list.go
  go/pkg/pwengine/api_user-delete-account.go
  go/pkg/pwengine/api_user-get-session.go
  go/pkg/pwengine/errors.go
  go/pkg/pwengine/helpers.go
  swagger.yaml
Labels: 🔍 Ready for Review

#268 chore: configure deleted_at field
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_user-delete-account.go
  swagger.yaml
Labels: 🔍 Ready for Review

#271 feat: pathwar compose ps
  go/cmd/pathwar/main.go
  go/go.mod
  go/go.sum
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#273 chore: add Organization.SoloSeason flag and restrict team creation
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_team-create.go
  go/pkg/pwengine/api_team-create_test.go
  go/pkg/pwengine/api_user-get-session.go
  go/pkg/pwengine/api_user-get-session_test.go
  swagger.yaml
Labels: 🔍 Ready for Review

#272 chore: fake cash, score, medals, achievements
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/entity.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwengine/api_team-list.go
  swagger.yaml
  tool/integration/Makefile
Labels: 🔍 Ready for Review

#275 Pwcompose ps
  go/go.mod
  go/go.sum
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: 🔍 Ready for Review

#274 fix: added '/' in the end of prefix if needed for compose prepare
  go/pkg/pwcompose/compose.go
Labels: ✅ Approved

#276 wip: pathwar compose down
  go/cmd/pathwar/main.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#277 chore: placedholder code for hypervisor
  AUTHORS
  go/cmd/pathwar/main.go
  go/go.sum
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
  go/pkg/pwhypervisor/daemon.go
  go/pkg/pwhypervisor/nginx.go
Labels: 🔍 Ready for Review

#278 chore: fix typo
  go/cmd/pathwar/main.go
Labels: 🔍 Ready for Review

#280 chore: bump deps
  go/go.mod
  go/go.sum
Labels: 🔍 Ready for Review

#283 chore: use direct fallback for goproxy
  go/Dockerfile
Labels: 🔍 Ready for Review

#281 fix: pw compose down by abridged hash fixed (needed to check one…
  go/pkg/pwcompose/compose.go
Labels: t/platform, ✅ Approved

#284 chore: refactor tests
  go/pkg/pwengine/api_challenge-get_test.go
  go/pkg/pwengine/api_challenge-subscription-validate_test.go
  go/pkg/pwengine/api_season-challenge-buy_test.go
  go/pkg/pwengine/api_season-challenge-get_test.go
  go/pkg/pwengine/api_season-challenge-list_test.go
  go/pkg/pwengine/api_team-get_test.go
  go/pkg/pwengine/api_team-list_test.go
  go/pkg/pwengine/api_user-set-preferences_test.go
Labels: 🔍 Ready for Review

#287 Pwcompose update
  go/cmd/pathwar/main.go
  go/pkg/pwcompose/compose.go
Labels: ✅ Approved

#286 chore: errcodes
  api/errcode.proto
  docs/gen.sum
  go/Makefile
  go/cmd/pathwar/main.go
  go/gen.sum
  go/go.mod
  go/pkg/errcode/doc.go
  go/pkg/errcode/errcode.pb.go
  go/pkg/errcode/error.go
  go/pkg/errcode/error_test.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwdb/db.go
  go/pkg/pwdb/errors.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwengine/api_challenge-get.go
  go/pkg/pwengine/api_challenge-get_test.go
  go/pkg/pwengine/api_challenge-list.go
  go/pkg/pwengine/api_challenge-subscription-close.go
  go/pkg/pwengine/api_challenge-subscription-close_test.go
  go/pkg/pwengine/api_challenge-subscription-validate.go
  go/pkg/pwengine/api_challenge-subscription-validate_test.go
  go/pkg/pwengine/api_organization-list.go
  go/pkg/pwengine/api_season-challenge-buy.go
  go/pkg/pwengine/api_season-challenge-buy_test.go
  go/pkg/pwengine/api_season-challenge-get.go
  go/pkg/pwengine/api_season-challenge-get_test.go
  go/pkg/pwengine/api_season-challenge-list.go
  go/pkg/pwengine/api_season-challenge-list_test.go
  go/pkg/pwengine/api_team-accept-invite.go
  go/pkg/pwengine/api_team-create.go
  go/pkg/pwengine/api_team-create_test.go
  go/pkg/pwengine/api_team-get.go
  go/pkg/pwengine/api_team-get_test.go
  go/pkg/pwengine/api_team-list.go
  go/pkg/pwengine/api_team-list_test.go
  go/pkg/pwengine/api_team-send-invite.go
  go/pkg/pwengine/api_tool-info_test.go
  go/pkg/pwengine/api_tool-status_test.go
  go/pkg/pwengine/api_user-delete-account.go
  go/pkg/pwengine/api_user-delete-account_test.go
  go/pkg/pwengine/api_user-get-session.go
  go/pkg/pwengine/api_user-get-session_test.go
  go/pkg/pwengine/api_user-set-preferences.go
  go/pkg/pwengine/api_user-set-preferences_test.go
  go/pkg/pwengine/auth.go
  go/pkg/pwengine/engine.go
  go/pkg/pwengine/errors.go
  go/pkg/pwengine/testing_test.go
  go/pkg/pwhypervisor/daemon.go
  go/pkg/pwserver/server.go
  go/pkg/pwsso/client.go
  go/pkg/pwsso/keycloak.go
  go/pkg/pwsso/token.go
Labels: ✅ Approved
