Repository pathwar/pathwar, pull requests merged in 2019-12, with the labels that each got.

#282 wip Pwhypervisor nginx
  .gitignore
  api/errcode.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/go.mod
  go/go.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwhypervisor/config.go
  go/pkg/pwhypervisor/nginx.go
Labels: t/platform, ✅ Approved

#292 feat: added RestartPolicy "unless-stopped" to all containers bef…
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#290 fix: config check
  go/pkg/pwhypervisor/nginx.go
Labels: t/platform, ✅ Approved

#297 fix: deploy
  deployments/platform-dev/docker-compose.yml
Labels: 🔍 Ready for Review

#295 chore: agent API placeholder
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/go.mod
  go/go.sum
  go/pkg/pwapi/api_agent-list-instances.go
  go/pkg/pwapi/api_agent-list.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#298 feat: pathwar compose up --force-recreate
  api/errcode.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwcompose/compose.go
Labels: ✅ Approved

#300 feat: pwcompose up now injects pwinit binary in containers before sta…
  api/errcode.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwcompose/compose.go
Labels: 🔍 Ready for Review

#302 feat: pathwar compose up injects a config file that contains challeng…
  api/errcode.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#303 chore: use pwinit.Config from pwcompose
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#301 feat: pathwar compose prepare --no-push
  go/pkg/pwcompose/compose.go
Labels: ✅ Approved

#304 chore: placeholder code for agent daemon
  go/cmd/pathwar/main.go
  go/pkg/pwagent/daemon.go
Labels: ✅ Approved

#305 feat: pwagent daemon
  api/errcode.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/go.mod
  go/go.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#308 feat: pwcompose down --with-nginx
  api/errcode.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: ✅ Approved

#309 fix: pwcompose down --with-nginx now rm nginx proxy container
  go/pkg/pwcompose/compose.go
Labels: 🔍 Ready for Review

#311 chore: share listener for both HTTP and gRPC
  deployments/platform-dev/docker-compose.yml
  go/cmd/pathwar/main.go
  go/docker-compose.yml
  go/go.mod
  go/go.sum
  go/pkg/pwapi/api_tool-status.go
  go/pkg/pwapi/server.go
  go/pkg/pwapi/server_test.go
  go/pkg/pwapi/testing.go
  go/pkg/pwapi/testing_test.go
Labels: 🔍 Ready for Review

#307 feat: agent API
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/go.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_agent-list-instances.go
  go/pkg/pwapi/api_agent-list-instances_test.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_agent-register_test.go
  go/pkg/pwapi/api_challenge-list.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/testing_test.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/model_helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#294 WIP chore: handle slow tests
  .circleci/config.yml
  go/internal/testutil/skip.go
Labels: t/platform, 🚧 WIP

#312 chore: use assert testing library
  go/pkg/errcode/error_test.go
  go/pkg/pwapi/api_challenge-get_test.go
  go/pkg/pwapi/api_challenge-subscription-close_test.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_season-challenge-get_test.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/api_team-create_test.go
  go/pkg/pwapi/api_team-get_test.go
  go/pkg/pwapi/api_team-list_test.go
  go/pkg/pwapi/api_tool-info_test.go
  go/pkg/pwapi/api_tool-status_test.go
  go/pkg/pwapi/api_user-delete-account_test.go
  go/pkg/pwapi/api_user-get-session_test.go
  go/pkg/pwapi/api_user-set-preferences_test.go
  go/pkg/pwapi/testing_test.go
Labels: 🔍 Ready for Review

#269 feat: coupons
  .circleci/config.yml
  api/pwapi.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwapi/api_coupon-validate.go
  go/pkg/pwapi/api_coupon-validate_test.go
  go/pkg/pwapi/api_tool-info_test.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwapi/testing.go
  go/pkg/pwdb/migrations.go
  swagger.yaml
Labels: t/platform, 🔍 Ready for Review

#310 pwinit overrides challenge entrypoint
  api/errcode.proto
  challenges/web/training-http/front/Dockerfile
  challenges/web/training-http/front/on-init
  docs/gen.sum
  go/cmd/pwinit/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/config.go
Labels: 🔍 Ready for Review
