Repository pathwar/pathwar, pull requests merged in 2020-10, with the labels that each got.

#607 chore: configure zapconfig
  go.mod
  go.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/cli.go
  go/cmd/pathwar/compose.go
  go/cmd/pathwar/main.go
  go/cmd/pathwar/util.go
  go/internal/testutil/logging.go
  go/pkg/errcode/error.go
  go/pkg/pwagent/update.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_admin_list-organizations.go
  go/pkg/pwapi/api_agent-list-instances_test.go
  go/pkg/pwapi/api_season-challenge-list.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/api_team-list.go
  go/pkg/pwapi/api_user-delete-account.go
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/server.go
  go/pkg/pwdb/db.go
  go/pkg/pwsso/keycloak.go
  tool/screenshoter/main.go
Labels: chore, 🔍 Ready for Review

#608 feat: if season is global, validated challenge are automatically acce…
  go/pkg/pwapi/api_challenge-subscription-validate.go
Labels: enhancement, 🔍 Ready for Review

#609 feat: testers can see testing season, admin can see all seasons
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/auth.go
Labels: enhancement, ✅ Approved

#611 fix: typo
  go/pkg/pwsso/keycloak.go
Labels: bug, ✅ Approved

#614 fix: removed compose_bundle and instance_config data from season chal…
  go/pkg/pwapi/api_season-challenge-get.go
  go/pkg/pwapi/api_season-challenge-list.go
Labels: bug, ✅ Approved

#612 fix: by default mariadb docker image uses utf8mb4 as encoding which i…
  deployments/keycloak/docker-compose.yml
Labels: bug, ✅ Approved

#613 feat: prefixed mysql development data volume name with pw so we don't…
  go/Makefile
  go/docker-compose.yml
  go/gen.sum
Labels: enhancement, ✅ Approved

#615 fix: moved keycloak.json file to static folder instead of public whic…
  web/static/keycloak.json
Labels: bug, ✅ Approved

#616 feat: cli create-team
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/cli.go
  go/gen.sum
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwdb/helpers.go
  swagger.yaml
Labels: enhancement, ✅ Approved

#617 feat: team invite
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/cli.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin_list-all.go
  go/pkg/pwapi/api_admin_season-add.go
  go/pkg/pwapi/api_team-accept-invite.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-send-invite.go
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwdb/entity.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/hooks.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: enhancement, ✅ Approved

#619 fix: team flow (cf https://github.com/pathwar/pathwar/issues/618)
  api/errcode.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_team-accept-invite.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-send-invite.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: bug, ✅ Approved

#621 fix: admin challenge add and admin season challenge add now uses Save…
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/api_admin-season-challenge-add.go
Labels: bug, ✅ Approved

#622 feat: admin redump challenge cli command
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/gen.sum
  go/pkg/pwapi/api_admin-challenge-redump.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#623 feat: added slug hooks for SeasonChallenge, ChallengeInstance, Challe…
  go/pkg/pwdb/hooks.go
Labels: enhancement, 🔍 Ready for Review

#624 fix: bug that made challenge instance in NeedRedump status block all …
  api/errcode.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
Labels: bug, ✅ Approved

#625 fix: challenge redump sql call didn't find the challenge instances
  go/pkg/pwapi/api_admin-challenge-redump.go
Labels: bug, ✅ Approved

#627 WIP feat: added challenge redump call after register
  challenges/_register.sh
  go/cmd/pathwar/compose.go
Labels: enhancement, 🚧 WIP

#626 fix: restore tests on CI
  .github/workflows/go.yml
  api/errcode.proto
  docs/gen.sum
  go.sum
  go/Makefile
  go/cmd/pathwar/depaware.txt
  go/cmd/pwinit/depaware.txt
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-create_test.go
  go/pkg/pwapi/api_user-get-session_test.go
  rules.mk
Labels: bug, 🔍 Ready for Review

#610 feat: New navigation
  web/src/components/SiteWrapper.js
  web/src/images/icon-close-filled.svg
  web/src/images/icon-mail.svg
  web/src/images/icon-notifications.svg
  web/src/images/icon-profile.svg
  web/src/images/icon-pwn-small.svg
  web/src/images/icon-pwn.svg
  web/src/images/island-light-mode-illustration-big.svg
  web/src/images/new-pathwar-logo-light-blue.svg
  web/src/pages/app.js
  web/src/styles/globalStyle.js
Labels: WIP, enhancement, ✅ Approved

#628 test: added unit tests for TeamSendInvite and TeamAcceptInvite
  go/pkg/pwapi/api_team-accept-invite.go
  go/pkg/pwapi/api_team-accept-invite_test.go
  go/pkg/pwapi/api_team-send-invite.go
  go/pkg/pwapi/api_team-send-invite_test.go
  go/pkg/pwapi/testing_test.go
  go/pkg/pwsso/testing.go
Labels: test, ✅ Approved

#629 chore: naming
  go/pkg/pwapi/api_admin-list-activities.go
  go/pkg/pwapi/api_admin-list-agents.go
  go/pkg/pwapi/api_admin-list-all.go
  go/pkg/pwapi/api_admin-list-challenge-subscriptions.go
  go/pkg/pwapi/api_admin-list-challenges.go
  go/pkg/pwapi/api_admin-list-coupons.go
  go/pkg/pwapi/api_admin-list-organizations.go
  go/pkg/pwapi/api_admin-list-teams.go
  go/pkg/pwapi/api_admin-list-users.go
  go/pkg/pwapi/api_admin-search.go
  go/pkg/pwapi/api_admin-season-add.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_season-challenge-get_test.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/api_team-accept-invite_test.go
  go/pkg/pwapi/api_team-create_test.go
  go/pkg/pwapi/api_team-get_test.go
  go/pkg/pwapi/api_team-list_test.go
  go/pkg/pwapi/api_team-send-invite_test.go
  go/pkg/pwapi/api_tool-status_test.go
  go/pkg/pwapi/api_user-delete-account_test.go
  go/pkg/pwapi/api_user-get-session_test.go
  go/pkg/pwapi/api_user-set-preferences_test.go
Labels: chore, ✅ Approved
