Repository pathwar/pathwar, pull requests merged in 2020-07, with the labels that each got.

#559 chore: tell renovate to run go mod tidy
  .github/renovate.json
Labels: 🔍 Ready for Review

#554 feat: Interface adjustments - Profile Button - UI/UX
  web/package-lock.json
  web/src/components/SiteWrapper.js
  web/src/pages/app.js
  web/src/pages/index.module.css
  web/src/state/seasonReducer.js
  web/src/styles/globalStyle.js
Labels: ✅ Approved

#562 fix: typos in challenges' dockerfiles + refactor
  .circleci/config.yml
  challenges/Makefile
  challenges/challenge.mk
  challenges/web/captcha-luigi/Makefile
  challenges/web/captcha-luigi/docker-compose.yml
  challenges/web/captcha-mario/Makefile
  challenges/web/captcha-mario/docker-compose.yml
  challenges/web/helloworld/Makefile
  challenges/web/helloworld/docker-compose.yml
  challenges/web/imageboard/Makefile
  challenges/web/imageboard/docker-compose.yml
  challenges/web/imageboard/front/Dockerfile
  challenges/web/training-brute/Makefile
  challenges/web/training-brute/docker-compose.yml
  challenges/web/training-brute/front/Dockerfile
  challenges/web/training-http/Makefile
  challenges/web/training-http/docker-compose.yml
  challenges/web/training-include/Makefile
  challenges/web/training-include/docker-compose.yml
  challenges/web/training-sqli/Makefile
  challenges/web/training-sqli/docker-compose.yml
  challenges/web/upload-hi/Makefile
  challenges/web/upload-hi/docker-compose.yml
Labels: bug, 🔍 Ready for Review

#563 chore: add new challenge helpers
  .gitignore
  challenges/challenge.mk
Labels: chore, 🔍 Ready for Review

#565 chore: configure CompileDaemon for auto-restarting go API and Agent
  AUTHORS
  go.mod
  go.sum
  go/Makefile
  go/gen.sum
  go/internal/tools/tools.go
Labels: chore, 🔍 Ready for Review

#566 chore: migrate circle to github actions
  .circleci/config.yml
  .dockerignore
  .github/workflows/challenges.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/protobuf.yml
  .github/workflows/release.yml
  .github/workflows/web.yml
  README.md
  challenges/Makefile
Labels: chore, 🔍 Ready for Review

#568 feat: add ascii-banners on long-running processes to help debugging
  go.mod
  go.sum
  go/cmd/pathwar/main.go
  go/cmd/pwinit/main.go
Labels: enhancement, 🔍 Ready for Review

#569 chore: refactor the main and the API in general
  .gitignore
  go/cmd/pathwar/main.go
  go/pkg/pwagent/docker.go
  go/pkg/pwagent/types.go
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/server.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwsso/client.go
Labels: chore, 🔍 Ready for Review

#570 chore: split some big files
  go/cmd/pathwar/main.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/register.go
  go/pkg/pwagent/types.go
  go/pkg/pwcompose/clean.go
  go/pkg/pwcompose/compose.go
  go/pkg/pwcompose/const.go
  go/pkg/pwcompose/helpers.go
  go/pkg/pwcompose/prepare.go
  go/pkg/pwcompose/ps.go
  go/pkg/pwcompose/up.go
Labels: chore, 🔍 Ready for Review

#572 chore: split main
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/agent.go
  go/cmd/pathwar/api.go
  go/cmd/pathwar/compose.go
  go/cmd/pathwar/main.go
  go/cmd/pathwar/misc.go
  go/cmd/pathwar/rawclient.go
  go/cmd/pathwar/util.go
Labels: chore, 🔍 Ready for Review

#564 feat: Challenge View-Page & Modals
  web/gatsby-config.js
  web/package-lock.json
  web/package.json
  web/src/components/ProtectedRoute.js
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCard.js
  web/src/components/challenges/ChallengeList.js
  web/src/components/challenges/ChallengeModal.js
  web/src/components/challenges/ChallengeSolveInstances.js
  web/src/components/challenges/ChallengeValidateForm.js
  web/src/components/challenges/ValidationsList.js
  web/src/components/season/AllTeamsOnSeasonList.js
  web/src/components/team/CreateTeamButton.js
  web/src/constants/actionTypes.js
  web/src/constants/metadata.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/ChallengesPage.js
  web/src/pages/SettingsPage.js
  web/src/pages/StatisticsPage.js
  web/src/pages/app.js
  web/src/pages/styles/ChallengeDetailsPage.module.css
  web/src/state/seasonReducer.js
  web/src/styles/globalStyle.js
  web/src/styles/layout/button.module.css
  web/src/styles/layout/loader.module.css
Labels: enhancement, ✅ Approved

#573 feat: 'pathwar cli'
  go/cmd/pathwar/cli.go
  go/cmd/pathwar/main.go
  go/pkg/pwapi/httpclient.go
Labels: enhancement, 🔍 Ready for Review

#574 feat: add slugs support
  api/pwdb.proto
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/pathwar/main_test.go
  go/gen.sum
  go/pkg/pwapi/server.go
  go/pkg/pwdb/hooks.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#575 feat: improve CLIs
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/cli.go
  go/gen.sum
  go/pkg/pwagent/docker.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_admin_list-challenges.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwdb/model_helpers.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#576 feat: new admin tools
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin-add-coupon.go
  go/pkg/pwapi/api_admin-ps.go
  go/pkg/pwapi/api_admin_list-activities.go
  go/pkg/pwapi/api_admin_list-agents.go
  go/pkg/pwapi/api_admin_list-challenge-subscriptions.go
  go/pkg/pwapi/api_admin_list-coupons.go
  go/pkg/pwapi/api_admin_list-organizations.go
  go/pkg/pwapi/api_admin_list-teams.go
  go/pkg/pwapi/api_admin_list-users.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_coupon-validate.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwdb/ascii.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/hooks.go
  go/pkg/pwdb/model_helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#577 feat: improve user & admin CLI + fix some edge cases in agent allocation
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go.mod
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/api.go
  go/cmd/pathwar/cli.go
  go/cmd/pathwar/util.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/errcode/error.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/docker.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/api_admin-challenge-instance-add.go
  go/pkg/pwapi/api_admin-season-challenge-add.go
  go/pkg/pwapi/api_admin_list-challenges.go
  go/pkg/pwapi/api_agent-list.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_season-challenge-list.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwcompose/up.go
  go/pkg/pwdb/ascii.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/hooks.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwdb/testing.go
  swagger.yaml
  web/tests/api.test.js
Labels: enhancement, 🔍 Ready for Review

#578 fix: Buy callenge routine new params (flavor_id, season_id)
  web/src/actions/seasons.js
  web/src/api/seasons.js
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeList.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/ChallengesPage.js
  web/src/state/seasonReducer.js
Labels: bug, ✅ Approved

#579 chore: cleanup
  api/errcode.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/cli.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_admin-add-coupon.go
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/api_admin-season-challenge-add.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_season-challenge-get_test.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-create_test.go
  go/pkg/pwapi/api_team-get_test.go
  go/pkg/pwapi/api_team-list_test.go
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/api_user-get-session_test.go
  go/pkg/pwapi/api_user-set-preferences_test.go
  go/pkg/pwapi/testing_test.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwdb/testing.go
  swagger.yaml
  web/tests/api.test.js
Labels: chore, 🔍 Ready for Review

#580 fix: typo in captcha-luigi on-init
  challenges/web/captcha-luigi/front/on-init
Labels: bug, ✅ Approved

#581 fix: typo in captcha-mario on-init file
  challenges/web/captcha-mario/front/on-init
Labels: bug, ✅ Approved

#583 fix: comment not required in challenge validation
  web/src/components/challenges/ChallengeValidateForm.js
Labels: bug, ✅ Approved

#582 fix: active season id on preferences post, remove tags is_latest and version
  web/src/actions/userSession.js
  web/src/components/challenges/ChallengeCard.js
  web/src/pages/ChallengeDetailsPage.js
Labels: bug, ✅ Approved, 🔍 Ready for Review

#585 feat: various fixes for tomorrow's session
  api/pwdb.proto
  challenges/challenge.mk
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/compose.go
  go/cmd/pathwar/util.go
  go/gen.sum
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwcompose/prepare.go
  go/pkg/pwcompose/types.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#586 feat: Update statistics table related to teams, show cash and more
  web/src/components/season/AllTeamsOnSeasonList.js
  web/src/pages/StatisticsPage.js
Labels: enhancement, ✅ Approved

#587 feat: Update challenge list card, and internal behavior of status showing and buttons
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCard.js
  web/src/components/challenges/ChallengeSolveInstances.js
  web/src/pages/ChallengeDetailsPage.js
Labels: enhancement, ✅ Approved

#588 feat: various fixes and configuration update
  Makefile
  api/pwdb.proto
  challenges/_register.sh
  challenges/web/captcha-luigi/docker-compose.yml
  challenges/web/captcha-mario/docker-compose.yml
  challenges/web/helloworld/docker-compose.yml
  challenges/web/imageboard/docker-compose.yml
  challenges/web/training-brute/docker-compose.yml
  challenges/web/training-http/docker-compose.yml
  challenges/web/training-include/docker-compose.yml
  challenges/web/training-sqli/docker-compose.yml
  challenges/web/upload-hi/docker-compose.yml
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/cli.go
  go/cmd/pathwar/compose.go
  go/gen.sum
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/api_season-challenge-list.go
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/model_helpers.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwdb/testing.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#589 feat: refactor passphrase generateor + fix admin redump
  go/pkg/pwagent/docker.go
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/api_admin-redump.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwdb/helpers.go
Labels: enhancement, 🔍 Ready for Review

#590 fix: UI General, challenge card, logo, remove profile menu
  web/src/components/SiteWrapper.js
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCard.js
  web/src/pages/ChallengeDetailsPage.js
Labels: bug, ✅ Approved
