Repository pathwar/pathwar, pull requests merged in 2020-03, with the labels that each got.

#431 fix: added screenshoter bin to gitignore file
  .gitignore
Labels: 🔍 Ready for Review

#430 feat: api add challenge
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: ✅ Approved

#433 feat: coupon money
  api/errcode.proto
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_coupon-validate.go
  go/pkg/pwapi/api_coupon-validate_test.go
Labels: 🔍 Ready for Review

#434 WIP feat: restricted area
  api/errcode.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/api_admin-ps.go
  go/pkg/pwapi/api_admin-redump.go
  go/pkg/pwapi/api_agent-list-instances.go
  go/pkg/pwapi/api_agent-list-instances_test.go
  go/pkg/pwapi/api_agent-list.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwapi/auth.go
  go/pkg/pwapi/server.go
  go/pkg/pwsso/testing.go
  go/pkg/pwsso/token.go
Labels: 🚧 WIP

#432 Agent update state
  api/errcode.proto
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/update.go
  go/pkg/pwapi/api_admin-challenge-add.go
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwcompose/compose.go
  swagger.yaml
Labels: ✅ Approved

#401 feat: error stack traces
  go.mod
  go/pkg/errcode/error.go
Labels: t/platform, 🔍 Ready for Review

#437 chore: bump rulesmk
  rules.mk
Labels: 🔍 Ready for Review

#440 feat: add agent-dev deployment
  .dockerignore
  .gitignore
  Dockerfile
  deployments/agent-dev/Makefile
  deployments/agent-dev/docker-compose.yml
  deployments/platform-dev/Makefile
  deployments/platform-dev/docker-compose.yml
  go/Makefile
  go/gen.sum
  tool/docker-agent/Dockerfile
Labels: 🔍 Ready for Review

#441 feat: add watchtower
  deployments/watchtower/Makefile
  deployments/watchtower/docker-compose.yml
Labels: 🔍 Ready for Review

#443 feat: configure opentracing
  api/errcode.proto
  docs/gen.sum
  go.mod
  go.sum
  go/Makefile
  go/cmd/pathwar/main.go
  go/cmd/pathwar/main_test.go
  go/docker-compose.dev.yml
  go/docker-compose.yml
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwagent/update.go
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwapi/server.go
  go/pkg/pwapi/tracing.go
Labels: 🔍 Ready for Review

#445 feat: agent register
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwagent/types.go
  go/pkg/pwapi/api_agent-list-instances.go
  go/pkg/pwapi/api_agent-list-instances_test.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#446 fix: panic for sso token with multiple clients
  go/pkg/pwapi/server.go
  go/pkg/pwsso/token.go
Labels: 🔍 Ready for Review

#447 fix: repair forestadmin dev deployment
  deployments/platform-dev/docker-compose.yml
  tool/forestadmin/Dockerfile
Labels: 🔍 Ready for Review

#449 feat: up-to-date docker agent
  Dockerfile.agent
  tool/docker-agent/Dockerfile
Labels: 🔍 Ready for Review

#448 feat: use hostname as default agent name
  go/cmd/pathwar/main.go
Labels: 🔍 Ready for Review

#450 feat: new agent-dev deployment helper
  Dockerfile.agent
  deployments/agent-dev/Makefile
Labels: 🔍 Ready for Review

#451 fix: docker agent build
  Dockerfile.agent
Labels: 🔍 Ready for Review

#439 feat: api add challenge flavor
  api/errcode.proto
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin-challenge-flavor-add.go
  go/pkg/pwapi/api_admin-challenge-instance-add.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  swagger.yaml
Labels: ✅ Approved

#453 feat: on season challenge validation, instances are redumped automati…
  go/pkg/pwapi/api_agent-update-state.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
Labels: ✅ Approved

#452 feat: refactor challenge listing
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/pathwar/main.go
  go/gen.sum
  go/pkg/pwagent/daemon.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwagent/types.go
  go/pkg/pwapi/api_agent-register.go
  go/pkg/pwapi/api_season-challenge-list.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/model_helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#270 feature: init team flow - team creating integration and stamp card
  web/gatsby-node.js
  web/package-lock.json
  web/package.json
  web/src/actions/seasons.js
  web/src/api/seasons.js
  web/src/components/ProtectedRoute.js
  web/src/components/season/AllTeamsOnSeasonList.js
  web/src/components/season/style.module.css
  web/src/components/team/CreateTeamStampCard.js
  web/src/constants/actionTypes.js
  web/src/pages/SeasonPage.js
  web/src/pages/app.js
  web/src/state/seasonReducer.js
Labels: t/front, ✅ Approved
