Repository pathwar/pathwar, pull requests merged in 2020-06, with the labels that each got.

#509 fix: remove unused field
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/helpers.go
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: 🔍 Ready for Review

#512 feat: replaced utf8 sql charset by utf8mb4
  api/pwdb.proto
  deployments/platform-dev/docker-compose.yml
  docs/gen.sum
  go/cmd/pathwar/main.go
  go/docker-compose.yml
  go/gen.sum
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/pwdb.pb.go
Labels: ✅ Approved

#515 fix: make pathwar api killable with signals
  go.mod
  go.sum
  go/cmd/pathwar/main.go
  go/pkg/pwapi/server.go
Labels: 🔍 Ready for Review

#516 chore: run golangci-lint only on github actions
  .circleci/config.yml
  .github/workflows/ci.yml
Labels: 🔍 Ready for Review

#517 fix: run migrations in transactions
  go/pkg/pwdb/migrations.go
Labels: 🔍 Ready for Review

#518 fix: Check for browser on 404 to prevent page blink on gatsby build
  web/src/pages/404.js
Labels: ✅ Approved

#520 Creating eslint configuration for "web" folder
  web/.eslintignore
  web/.eslintrc.json
  web/gatsby-browser.js
  web/gatsby-config.js
  web/gatsby-node.js
  web/gatsby-ssr.js
  web/package-lock.json
  web/package.json
  web/src/actions/organizations.js
  web/src/actions/seasons.js
  web/src/actions/userSession.js
  web/src/api/index.js
  web/src/api/organizations.js
  web/src/api/seasons.js
  web/src/api/userSession.js
  web/src/components/ProtectedRoute.js
  web/src/components/SiteWrapper.js
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCloseButton.js
  web/src/components/challenges/ChallengeList.js
  web/src/components/challenges/ChallengeValidateButton.js
  web/src/components/challenges/ValidationsList.js
  web/src/components/coupon/ValidateCouponButton.js
  web/src/components/organizations/AllOrganizationsList.js
  web/src/components/organizations/OrganizationStatsStampCard.js
  web/src/components/organizations/UserOrganizationsList.js
  web/src/components/season/AllSeasonsList.js
  web/src/components/season/AllTeamsOnSeasonList.js
  web/src/components/team/CreateTeamButton.js
  web/src/constants/actionTypes.js
  web/src/pages/404.js
  web/src/pages/AllSeasonsPage.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/DashboardPage.js
  web/src/pages/LogoutPage.js
  web/src/pages/SeasonPage.js
  web/src/pages/SettingsPage.js
  web/src/pages/TeamDetailsPage.js
  web/src/pages/app.js
  web/src/pages/index.js
  web/src/state/ReduxWrapper.js
  web/src/state/index.js
  web/src/state/organizationsReducer.js
  web/src/state/seasonReducer.js
  web/src/state/userSessionReducer.js
  web/tests/api.test.js
  web/tests/config/jest/__mocks__/file-mock.js
  web/tests/config/jest/jest-preprocess.js
  web/tests/config/jest/loadershim.js
  web/tests/jest.config.js
Labels: ✅ Approved

#505 feat: New theme, new landing implementation
  web/.env.development
  web/.env.production
  web/.eslintrc
  web/.prettierrc
  web/gatsby-config.js
  web/package-lock.json
  web/package.json
  web/src/actions/seasons.js
  web/src/components/ProtectedRoute.js
  web/src/components/SiteWrapper.js
  web/src/images/hook-d-icon.svg
  web/src/images/hook-l-icon.svg
  web/src/images/island-light-mode-illustration.svg
  web/src/images/landing-island-darkmode-illustration.svg
  web/src/images/map-d-icon.svg
  web/src/images/map-l-icon.svg
  web/src/images/new-pathwar-logo-dark-blue.png
  web/src/images/new-pathwar-logo-dark-blue.svg
  web/src/images/new-pathwar-logo-grey.svg
  web/src/images/new-pathwar-logo-light-purple.svg
  web/src/images/ship-d-icon.svg
  web/src/images/ship-l-icon.svg
  web/src/pages/app.js
  web/src/pages/index.js
  web/src/state/ReduxWrapper.js
  web/src/styles/globalStyle.js
  web/src/styles/themes.js
Labels: ✅ Approved

#526 fix: blank details page when challenge not purchased, css normalize
  web/src/components/challenges/ChallengeCloseButton.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/styles/globalStyle.js
Labels: 🔍 Ready for Review

#529 Add netlify plugins to "assets" site
  assets/.netlify/netlify.toml
  assets/.netlify/package-lock.json
  assets/.netlify/package.json
Labels: ✅ Approved

#528 fix: Sets dark theme based on preferences from the user, code of conduct link
  web/src/pages/index.js
  web/src/styles/globalStyle.js
Labels: ✅ Approved

#535 chore: prepare web for new go import (#531)
  web/static/_redirects
  web/static/goget-pathwar-land-pathwar.html
Labels: 🔍 Ready for Review

#541 feat(web): enable sentry (#534)
  web/package-lock.json
  web/package.json
  web/src/pages/app.js
Labels: 🔍 Ready for Review

#540 feat(go): configure sentry (#534)
  AUTHORS
  deployments/agent-dev/docker-compose.yml
  deployments/platform-dev/.env.example
  deployments/platform-dev/docker-compose.yml
  go.mod
  go.sum
  go/cmd/pathwar/main.go
  go/cmd/pathwar/main_test.go
  go/pkg/pwapi/server.go
Labels: 🔍 Ready for Review

#542 fix: Page double loading to check auth
  web/src/components/ProtectedRoute.js
Labels: ✅ Approved

#543 fix: Repeated call, missing calls when SPA navigating
  web/package-lock.json
  web/src/actions/seasons.js
  web/src/pages/SeasonPage.js
Labels: ✅ Approved

#546 feat: automatically retry to connect to MySQL on startup if connection is not yet ready
  go/Makefile
  go/cmd/pathwar/main.go
  go/gen.sum
Labels: 🔍 Ready for Review

#547 fix: api now removes previous instances from an agent when it is regi…
  go/pkg/pwapi/api_agent-register.go
Labels: ✅ Approved

#548 feat: show pathwar's nginx container in 'pathwar compose ps'
  go/pkg/pwcompose/compose.go
Labels: ✅ Approved

#550 fix: added .vscode to gitignore file
  .gitignore
Labels: 🔍 Ready for Review

#551 fix: updated forestadmin files
  tool/forestadmin/.forestadmin-schema.json
  tool/forestadmin/app.js
  tool/forestadmin/docker-compose.yml
  tool/forestadmin/forest/challenge-flavor.js
  tool/forestadmin/forest/challenge-instance.js
  tool/forestadmin/forest/challenge-subscription.js
  tool/forestadmin/forest/challenge-validation.js
  tool/forestadmin/forest/coupon-validation.js
  tool/forestadmin/forest/inventory-item.js
  tool/forestadmin/forest/organization-member.js
  tool/forestadmin/forest/season-challenge.js
  tool/forestadmin/forest/team-member.js
  tool/forestadmin/forest/whoswho-attempt.js
  tool/forestadmin/middlewares/forestadmin.js
  tool/forestadmin/models/achievement.js
  tool/forestadmin/models/agent.js
  tool/forestadmin/models/challenge-flavor.js
  tool/forestadmin/models/challenge-instance.js
  tool/forestadmin/models/challenge-subscription.js
  tool/forestadmin/models/challenge-validation.js
  tool/forestadmin/models/challenge.js
  tool/forestadmin/models/coupon-validation.js
  tool/forestadmin/models/coupon.js
  tool/forestadmin/models/inventory-item.js
  tool/forestadmin/models/migrations.js
  tool/forestadmin/models/notification.js
  tool/forestadmin/models/organization-member.js
  tool/forestadmin/models/organization.js
  tool/forestadmin/models/season-challenge.js
  tool/forestadmin/models/season.js
  tool/forestadmin/models/team-member.js
  tool/forestadmin/models/team.js
  tool/forestadmin/models/user.js
  tool/forestadmin/models/whoswho-attempt.js
  tool/forestadmin/package-lock.json
  tool/forestadmin/package.json
  tool/forestadmin/routes/achievement.js
  tool/forestadmin/routes/agent.js
  tool/forestadmin/routes/challenge-flavor.js
  tool/forestadmin/routes/challenge-instance.js
  tool/forestadmin/routes/challenge-subscription.js
  tool/forestadmin/routes/challenge-validation.js
  tool/forestadmin/routes/challenge.js
  tool/forestadmin/routes/coupon-validation.js
  tool/forestadmin/routes/coupon.js
  tool/forestadmin/routes/inventory-item.js
  tool/forestadmin/routes/migrations.js
  tool/forestadmin/routes/notification.js
  tool/forestadmin/routes/organization-member.js
  tool/forestadmin/routes/organization.js
  tool/forestadmin/routes/season-challenge.js
  tool/forestadmin/routes/season.js
  tool/forestadmin/routes/team-member.js
  tool/forestadmin/routes/team.js
  tool/forestadmin/routes/user.js
  tool/forestadmin/routes/whoswho-attempt.js
Labels: ✅ Approved

#545 fix: Console warnings from tabler and gatsby + react helmet
  web/package-lock.json
  web/package.json
  web/src/components/SiteWrapper.js
Labels: ✅ Approved

#552 feat: added npm run start:local-api to start a front server connected…
  web/package.json
Labels: ✅ Approved

#553 chore: mark new attributes as linguist-vendored + add check script
  .gitattributes
  rules.mk
Labels: 🔍 Ready for Review

#555 refactor: renamed "organizations" field to "teams" in Season proto me…
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/pwdb/pwdb.pb.go
  swagger.yaml
Labels: ✅ Approved

#556 WIP feat: add activity support
  .golangci.yml
  api/pwdb.proto
  docs/gen.sum
  go.sum
  go/gen.sum
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/api_coupon-validate.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwapi/api_user-delete-account.go
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/api_user-get-session_test.go
  go/pkg/pwapi/api_user-set-preferences.go
  go/pkg/pwapi/testing_test.go
  go/pkg/pwdb/entity.go
  go/pkg/pwdb/pwdb.pb.go
Labels: 🚧 WIP

#557 feat: money
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  docs/gen.sum
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_team-get.go
  go/pkg/pwapi/api_team-list.go
  go/pkg/pwapi/api_user-get-session.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwdb/migrations.go
  go/pkg/pwdb/model_helpers.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwdb/testing.go
  swagger.yaml
Labels: 🔍 Ready for Review
