Repository pathwar/pathwar, pull requests merged in 2022-03, with the labels that each got.

#704 feat: Refresh keycloak token, inform user when session expires
  web/src/components/ProtectedRoute.js
Labels: enhancement, ✅ Approved

#705 fix: Remove footer lorem ipsum, insert link in CTA
  web/src/pages/index.js
Labels: bug, 🔍 Ready for Review

#708 fix: Adjust static parts of code in web, update environment variables system
  web/.env.development
  web/.env.integration
  web/.env.production
  web/.env.test
  web/README.md
  web/gatsby-config.js
  web/src/pages/index.js
  web/static/keycloak.json
Labels: bug, 🔍 Ready for Review

#706 chore: fix crowdin config for challenges
  .gitignore
  crowdin-challenges.yml
Labels: 🔍 Ready for Review, chore

#710 chore: update netlify config
  web/.env.production
  web/netlify.toml
Labels: 🔍 Ready for Review, chore

#712 chore: Insert GATSBY prefix in env vars, remove env.production
  web/.env.development
  web/.env.integration
  web/.env.production
  web/.env.test
  web/gatsby-config.js
  web/gatsby-node.js
  web/netlify.toml
  web/src/api/index.js
  web/src/pages/index.js
Labels: 🔍 Ready for Review, chore

#713 chore: update gatsby env
  web/netlify.toml
Labels: 🔍 Ready for Review, chore

#714 chore: adjust var in file
  web/src/components/SiteWrapper.js
Labels: 🔍 Ready for Review, chore

#717 chore: multi-deployment improvements
  deployments/agent-dev/.env.example
  deployments/agent-dev/.gitignore
  deployments/agent-dev/Makefile
  deployments/agent-dev/docker-compose.yml
  deployments/keycloak/docker-compose.yml
  deployments/keycloak/themes/pathwar/login/register.ftl
  deployments/platform-dev/Makefile
  deployments/platform-dev/docker-compose.yml
  go/cmd/pathwar/agent.go
  go/pkg/pwsso/token.go
  web/static/503.html
Labels: 🔍 Ready for Review, chore

#722 feat: new gatsby main 404 page
  web/src/pages/404.js
  web/src/translations/en.json
  web/src/translations/es.json
  web/src/translations/fr.json
  web/src/translations/it.json
  web/src/translations/pt.json
  web/src/translations/ru.json
  web/src/translations/zh.json
Labels: enhancement, ✅ Approved

#721 fix: hide not used menu entries
  web/src/components/SiteWrapper.js
Labels: bug, ✅ Approved

#729 feat: New challenge list design
  web/src/components/Button.js
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCard.js
  web/src/components/challenges/ChallengeList.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/app.js
  web/src/styles/globalStyle.js
  web/src/styles/themes.js
  web/src/translations/en.json
  web/src/translations/es.json
  web/src/translations/fr.json
  web/src/translations/it.json
  web/src/translations/pt.json
  web/src/translations/ru.json
  web/src/translations/zh.json
  web/src/utils/generateLightColorHex.js
Labels: enhancement, ✅ Approved

#728 feat: Captcha Luigi multilanguage
  challenges/web/captcha-luigi/front/Dockerfile
  challenges/web/captcha-luigi/front/translations/en_US/LC_MESSAGES/messages.mo
  challenges/web/captcha-luigi/front/translations/en_US/LC_MESSAGES/messages.po
  challenges/web/captcha-luigi/front/translations/fr_FR/LC_MESSAGES/messages.mo
  challenges/web/captcha-luigi/front/translations/fr_FR/LC_MESSAGES/messages.po
  challenges/web/captcha-luigi/front/translations/messages.pot
  challenges/web/captcha-luigi/front/www/LocaleManager.php
  challenges/web/captcha-luigi/front/www/index.php
  challenges/web/captcha-luigi/front/www/style.css
Labels: enhancement, ✅ Approved

#727 feat: Captcha-Mario multilanguage
  challenges/web/captcha-mario/front/Dockerfile
  challenges/web/captcha-mario/front/translations/en_US/LC_MESSAGES/messages.mo
  challenges/web/captcha-mario/front/translations/en_US/LC_MESSAGES/messages.po
  challenges/web/captcha-mario/front/translations/fr_FR/LC_MESSAGES/messages.mo
  challenges/web/captcha-mario/front/translations/fr_FR/LC_MESSAGES/messages.po
  challenges/web/captcha-mario/front/translations/messages.pot
  challenges/web/captcha-mario/front/www/LocaleManager.php
  challenges/web/captcha-mario/front/www/index.php
  challenges/web/captcha-mario/front/www/style.css
Labels: enhancement, ✅ Approved

#725 feat: hello-world multilanguage
  challenges/web/helloworld/front/Dockerfile
  challenges/web/helloworld/front/on-init
  challenges/web/helloworld/front/translations/en_US/messages.mo
  challenges/web/helloworld/front/translations/en_US/messages.po
  challenges/web/helloworld/front/translations/fr_FR/LC_MESSAGES/messages.mo
  challenges/web/helloworld/front/translations/fr_FR/LC_MESSAGES/messages.po
  challenges/web/helloworld/front/translations/genPotFile.php
  challenges/web/helloworld/front/translations/messages.pot
  challenges/web/helloworld/front/www/.htaccess
  challenges/web/helloworld/front/www/classes/LocaleManager.php
  challenges/web/helloworld/front/www/index.php
  challenges/web/helloworld/front/www/templates/index.html
  challenges/web/helloworld/front/www/templates/you-lose.html
  challenges/web/helloworld/front/www/templates/you-win.html
Labels: enhancement, ✅ Approved

#734 fix(challenge-list-review): Overall UI/UX adjusts in challenge list after review
  web/src/components/challenges/ChallengeBuyButton.js
  web/src/components/challenges/ChallengeCard.js
  web/src/components/challenges/ChallengeList.js
  web/src/components/challenges/ChallengeModal.js
  web/src/state/seasonReducer.js
  web/src/translations/en.json
  web/src/translations/es.json
  web/src/translations/fr.json
  web/src/translations/it.json
  web/src/translations/pt.json
  web/src/translations/ru.json
  web/src/translations/zh.json
Labels: bug, ✅ Approved

#735 chore: increase challenges density
  web/src/components/challenges/ChallengeCard.js
Labels: 🔍 Ready for Review, chore

#737 chore: various improvements
  AUTHORS
  Dockerfile
  Dockerfile.agent
  go/Makefile
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/depaware.txt
  go/cmd/pathwar/util.go
  go/gen.sum
  rules.mk
Labels: 🔍 Ready for Review, chore

#740 fix: Adjust keycloak to open in new tab, remove appIsRoot config, remove Index component
  web/.env.development
  web/gatsby-node.js
  web/src/components/SiteWrapper.js
  web/src/pages/app.js
  web/src/pages/index.js
Labels: bug, 🔍 Ready for Review

#741 fix: Wallet - adjust wallet to update after validation and purchase
  web/src/state/userSessionReducer.js
Labels: bug, 🔍 Ready for Review

#742 fix: (app-route) - remove remaining app route
  web/src/pages/ChallengeDetailsPage.js
  web/src/pages/app.js
  web/src/translations/en.json
  web/src/translations/es.json
  web/src/translations/fr.json
  web/src/translations/it.json
  web/src/translations/pt.json
  web/src/translations/ru.json
  web/src/translations/zh.json
Labels: bug, ✅ Approved

#744 fix: Challenge details - tag color, apply card style in details page
  web/src/components/challenges/ChallengeCard.js
  web/src/pages/ChallengeDetailsPage.js
  web/src/utils/generateLightColorHex.js
Labels: bug, ✅ Approved

#745 fix: Challenge tags colors
  web/src/components/challenges/ChallengeCard.js
  web/src/config/tagMap.js
  web/src/pages/ChallengeDetailsPage.js
Labels: bug, ✅ Approved

#748 fix: add analytics script
  web/gatsby-config.js
  web/package-lock.json
  web/package.json
  web/src/pages/index.js
Labels: bug, 🔍 Ready for Review
