Repository pathwar/pathwar, pull requests merged in 2022-02, with the labels that each got.

#677 fix: docker build
  Dockerfile
  Dockerfile.agent
  go/internal/tools/tools.go
Labels: bug, 🔍 Ready for Review

#678 feat: various improvements
  .dockerignore
  Dockerfile
  Dockerfile.agent
  challenges/challenge.mk
  challenges/web/captcha-luigi/front/www/index.php
  challenges/web/captcha-mario/front/www/index.php
  challenges/web/imageboard/docker-compose.yml
  challenges/web/imageboard/front/on-init
  challenges/web/imageboard/mysql/bootstrap.sql
  challenges/web/training-brute/front/on-init
  challenges/web/training-brute/front/www/gandalf.jpg
  challenges/web/training-brute/front/www/index.php
  challenges/web/training-http/front/on-init
  challenges/web/training-include/front/www/include4.php
  challenges/web/training-include/front/www/pown.php
  deployments/agent-dev/.env.example
  deployments/agent-dev/Makefile
  deployments/agent-dev/docker-compose.yml
  go.sum
  go/Makefile
  go/cmd/pathwar/compose.go
  go/cmd/pathwar/depaware.txt
  go/cmd/pwinit/main.go
  go/gen.sum
  go/internal/tools/tools.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwcompose/composebin.go
  go/pkg/pwcompose/prepare.go
  go/pkg/pwcompose/types.go
  go/pkg/pwcompose/up.go
Labels: enhancement, 🔍 Ready for Review

#683 feat: various improvements
  api/pwapi.proto
  challenges/web/training-http/docker-compose.yml
  challenges/web/training-http/front/on-init
  challenges/web/training-http/front/www/post.php
  challenges/web/training-http/front/www/redir.php
  challenges/web/training-http/front/www/step1.php
  challenges/web/training-http/front/www/step2.php
  challenges/web/training-http/front/www/step4.php
  challenges/web/training-sqli/docker-compose.yml
  challenges/web/training-sqli/front/www/step1.php
  docs/gen.sum
  go.mod
  go.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/depaware.txt
  go/cmd/pwinit/depaware.txt
  go/gen.sum
  go/pkg/pwapi/api_admin-list-activities.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwdb/model_helpers.go
  swagger.yaml
Labels: enhancement, 🔍 Ready for Review

#688 chore: Proofread challenges copy
  challenges/web/helloworld/front/www/index.html
  challenges/web/helloworld/front/www/you-lose.html
  challenges/web/helloworld/front/www/you-win.html
  challenges/web/imageboard/front/www/index.php
  challenges/web/training-brute/front/www/index.php
  challenges/web/training-brute/front/www/source_2.txt
  challenges/web/training-http/front/www/default.php
  challenges/web/training-http/front/www/header.php
  challenges/web/training-http/front/www/step1.php
  challenges/web/training-http/front/www/step2.php
  challenges/web/training-http/front/www/step3.php
  challenges/web/training-http/front/www/step4.php
  challenges/web/training-include/front/www/home.php
  challenges/web/training-include/front/www/include1.php
  challenges/web/training-include/front/www/include2.php
  challenges/web/training-include/front/www/include3.php
  challenges/web/training-include/front/www/include4.php
  challenges/web/training-include/front/www/include5.php
  challenges/web/training-include/front/www/index.php
  challenges/web/training-include/front/www/passphrase.php
  challenges/web/training-sqli/front/www/default.php
  challenges/web/training-sqli/front/www/header.php
  challenges/web/training-sqli/front/www/step1.php
  challenges/web/training-sqli/front/www/step2.php
Labels: ✅ Approved, chore

#689 fix: training-http unique passphrase consistency
  challenges/web/training-http/front/www/step2.php
Labels: bug, ✅ Approved

#693 Upload-hi multi-language support
  challenges/web/upload-hi/front/Dockerfile
  challenges/web/upload-hi/front/on-init
  challenges/web/upload-hi/front/translations/fr_FR/LC_MESSAGES/message.mo
  challenges/web/upload-hi/front/translations/fr_FR/LC_MESSAGES/message.po
  challenges/web/upload-hi/front/www/LocaleManager.php
  challenges/web/upload-hi/front/www/index.php
Labels: ✅ Approved

#700 chore: Make dynamic app the root with ENV variable
  web/.env.development
  web/.env.production
  web/gatsby-config.js
  web/gatsby-node.js
  web/src/components/SiteWrapper.js
  web/src/pages/app.js
  web/src/pages/index.js
Labels: 🔍 Ready for Review, ✅ Approved, chore

#701 fix: Add a fallback client route for not found/created routes (e.g.: missions), adjust menu active style
  web/src/components/SiteWrapper.js
  web/src/pages/NotAvailablePage.js
  web/src/pages/app.js
  web/src/styles/globalStyle.js
  web/src/translations/en.json
  web/src/translations/es.json
  web/src/translations/fr.json
  web/src/translations/it.json
  web/src/translations/ru.json
  web/src/translations/zh.json
Labels: bug, 🔍 Ready for Review

#698 Training include multilanguage
  challenges/web/training-include/front/Dockerfile
  challenges/web/training-include/front/translations/en_US/LC_MESSAGES/messages.mo
  challenges/web/training-include/front/translations/en_US/LC_MESSAGES/messages.po
  challenges/web/training-include/front/translations/fr_FR/LC_MESSAGES/messages.mo
  challenges/web/training-include/front/translations/fr_FR/LC_MESSAGES/messages.po
  challenges/web/training-include/front/translations/messages.pot
  challenges/web/training-include/front/www/LocaleManager.php
  challenges/web/training-include/front/www/home.php
  challenges/web/training-include/front/www/include1.php
  challenges/web/training-include/front/www/include2.php
  challenges/web/training-include/front/www/include3.php
  challenges/web/training-include/front/www/include4.php
  challenges/web/training-include/front/www/include5.php
  challenges/web/training-include/front/www/index.php
Labels: ✅ Approved

#696 Training sqli challenge multilanguage
  challenges/web/training-sqli/front/Dockerfile
  challenges/web/training-sqli/front/on-init
  challenges/web/training-sqli/front/translations/README.md
  challenges/web/training-sqli/front/translations/en_US/LC_MESSAGES/messages.mo
  challenges/web/training-sqli/front/translations/en_US/LC_MESSAGES/messages.po
  challenges/web/training-sqli/front/translations/fr_FR/LC_MESSAGES/messages.mo
  challenges/web/training-sqli/front/translations/fr_FR/LC_MESSAGES/messages.po
  challenges/web/training-sqli/front/translations/messages.pot
  challenges/web/training-sqli/front/www/classes/LocaleManager.php
  challenges/web/training-sqli/front/www/classes/TplBlock.php
  challenges/web/training-sqli/front/www/default.php
  challenges/web/training-sqli/front/www/header.php
  challenges/web/training-sqli/front/www/index.php
  challenges/web/training-sqli/front/www/info.php
  challenges/web/training-sqli/front/www/phpinfo.php
  challenges/web/training-sqli/front/www/step1.php
  challenges/web/training-sqli/front/www/step1.txt
  challenges/web/training-sqli/front/www/step2.php
  challenges/web/training-sqli/front/www/step2.txt
  challenges/web/training-sqli/front/www/style.css
  challenges/web/training-sqli/front/www/templates/main.html
Labels: 🔍 Ready for Review
