Repository pathwar/pathwar, pull requests merged in 2022-09, with the labels that each got.

#770 test(ci): bump golangci-lint on CI
  .github/workflows/go.yml
Labels: 🔍 Ready for Review, test

#771 chore: update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔍 Ready for Review, chore

#769 feat: save score in DB
  go/cmd/pathwar/compose.go
  go/cmd/pathwar/main_test.go
  go/cmd/pathwar/util.go
  go/cmd/pwinit/main.go
  go/internal/randstring/randstring.go
  go/internal/tools/tools.go
  go/pkg/errcode/error_test.go
  go/pkg/pwagent/nginx.go
  go/pkg/pwapi/activity_test.go
  go/pkg/pwapi/api_admin-testing-season-user-add.go
  go/pkg/pwapi/api_agent-list-instances_test.go
  go/pkg/pwapi/api_agent-register_test.go
  go/pkg/pwapi/api_challenge-get_test.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/api_challenge-subscription-validate_test.go
  go/pkg/pwapi/api_coupon-validate_test.go
  go/pkg/pwapi/api_season-challenge-buy_test.go
  go/pkg/pwapi/api_season-challenge-get_test.go
  go/pkg/pwapi/api_season-challenge-list_test.go
  go/pkg/pwapi/api_team-accept-invite.go
  go/pkg/pwapi/api_team-accept-invite_test.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-create_test.go
  go/pkg/pwapi/api_team-get_test.go
  go/pkg/pwapi/api_team-list.go
  go/pkg/pwapi/api_team-list_test.go
  go/pkg/pwapi/api_team-send-invite.go
  go/pkg/pwapi/api_team-send-invite_test.go
  go/pkg/pwapi/api_user-set-preferences_test.go
  go/pkg/pwapi/helpers.go
  go/pkg/pwapi/server.go
  go/pkg/pwapi/tracing.go
  go/pkg/pwcompose/composebin.go
  go/pkg/pwcompose/up.go
  go/pkg/pwinit/inject.go
Labels: enhancement, 🔍 Ready for Review
