Repository pathwar/pathwar, pull requests merged in 2023-04, with the labels that each got.

#848 enable season rule system
  .github/workflows/go.yml
  api/errcode.proto
  api/pwapi.proto
  api/pwdb.proto
  api/pwes.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/gen.sum
  go/pkg/errcode/errcode.pb.go
  go/pkg/pwapi/api_admin-list-activities.go
  go/pkg/pwapi/api_admin-season-add.go
  go/pkg/pwapi/api_admin-update-season-metadata.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/api_coupon-validate.go
  go/pkg/pwapi/api_season-challenge-buy.go
  go/pkg/pwapi/api_team-accept-invite.go
  go/pkg/pwapi/api_team-create.go
  go/pkg/pwapi/api_team-send-invite.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwapi/season_rules.go
  go/pkg/pwapi/season_rules_test.go
  go/pkg/pwdb/pwdb.pb.go
  go/pkg/pwes/event_handler.go
  go/pkg/pwes/execute-season-close.go
  go/pkg/pwes/execute_season-open.go
  go/pkg/pwes/pwes.pb.go
  seasons/template/template_rules.yml
  swagger.yaml
  web/src/actions/seasons.js
  web/src/actions/userSession.js
  web/src/constants/apiErrorsCode.js
Labels: 🔍 Ready for Review

#853 fix(web): style button
  web/src/components/team/CreateTeamButton.js
Labels: 🔍 Ready for Review

#855 feat: add a way to dump season stats into CSV/JSON file
  api/pwapi.proto
  docs/gen.sum
  go/cmd/pathwar/admin.go
  go/cmd/pathwar/depaware.txt
  go/cmd/pathwar/util.go
  go/gen.sum
  go/pkg/pwapi/api_admin-season-stats.go
  go/pkg/pwapi/api_challenge-subscription-validate.go
  go/pkg/pwapi/httpclient.go
  go/pkg/pwapi/pwapi.pb.go
  go/pkg/pwapi/pwapi.pb.gw.go
  go/pkg/pwes/rebuild.go
  swagger.yaml
Labels: 🔍 Ready for Review

#857 feat(web): redux add update list of teams on create team action
  web/src/state/organizationsReducer.js
Labels: 🔍 Ready for Review

#858 fix(web): add details button in list team in organization details page
  web/src/components/organization/AllTeamsOnOrganization.js
Labels: 🔍 Ready for Review

#860 Fix the broken link to the challenge maintainers wiki
  challenges/README.md
Labels: ✅ Approved

#866 fix(web): add error msg for buying challenge cash issue
  web/src/constants/apiErrorsCode.js
Labels: 🔍 Ready for Review

#869 WIP: get rid of keycloack
  api/pwsso.proto
  docs/gen.sum
  go/cmd/pathwar/cli.go
  go/cmd/pathwar/util.go
  go/gen.sum
  go/pkg/pwsso/client.go
  go/pkg/pwsso/pwsso.pb.go
  go/pkg/pwsso/testing.go
  go/pkg/pwsso/token.go
  swagger.yaml
  web/.env.development
  web/.env.integration
  web/.env.test
  web/src/actions/userSession.js
  web/src/api/index.js
  web/src/api/userSession.js
  web/src/components/ProtectedRoute.js
  web/src/constants/actionTypes.js
  web/src/constants/userSession.js
  web/src/state/userSessionReducer.js
Labels: 🚧 WIP
